shell_extras_oh_my_zsh_repo: https://github.com/ohmyzsh/ohmyzsh.git
shell_extras_oh_my_zsh_dir: "{{ (ansible_facts['env'] | default({})).get('HOME', '') }}/.oh-my-zsh"
shell_extras_oh_my_zsh_custom: "{{ shell_extras_oh_my_zsh_dir }}/custom"
shell_extras_zsh_plugins:
  - repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins.git
    dest: "{{ shell_extras_oh_my_zsh_custom }}/plugins/autoupdate"
    version: master
  - repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ shell_extras_oh_my_zsh_custom }}/plugins/zsh-autosuggestions"
    version: master
  - repo: https://github.com/zsh-users/zsh-completions.git
    dest: "{{ shell_extras_oh_my_zsh_custom }}/plugins/zsh-completions"
    version: master
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ shell_extras_oh_my_zsh_custom }}/plugins/zsh-syntax-highlighting"
    version: master
