macos_cli_brew_packages:
  - curl
  - git
  - jq
  - gnupg
  - lynx
  - ncdu
  - neovim
  - python
  - rsync
  - tree
  - wget
  - zsh
  - coreutils
  - btop
  - kitty
  - starship
  - lsd
  - yazi
  - fzf
  - ripgrep
  - fastfetch
  - yt-dlp
  - ansible
  - powershell

macos_cli_cask_packages:
  - iterm2
