macos_cli_brew_packages:
  - yt-dlp
  - aria2
  - ffmpeg
  - node
  - chezmoi
  - zsh-autocomplete
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - coreutils
  - curl
  - git
  - jq
  - gnupg
  - mosh
  - lynx
  - ncdu
  - rsync
  - tree
  - wget
  - btop
  - starship
  - lsd
  - yazi
  - fzf
  - ripgrep
  - tealdeer
  - fastfetch
  - neovim
  - ansible
  - powershell
  - bat
  - fd
  - tmux
  - zoxide
  - mise

macos_cli_cask_packages:
  - ghostty
  - font-hack-nerd-font
