macos_cli_brew_packages:
  - yt-dlp
  - ffmpeg
  - node
  - chezmoi
  - zsh-autocomplete
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - coreutils
  - curl
  - git
  - jq
  - gnupg
  - lynx
  - ncdu
  - rsync
  - tree
  - wget
  - btop
  - starship
  - lsd
  - yazi
  - fzf
  - ripgrep
  - tealdeer
  - fastfetch
  - neovim
  - ansible
  - powershell

macos_cli_cask_packages:
  - kitty
  - font-fira-code
