common_core_brew_packages:
  - ansible
  - curl
  - git
  - jq
  - gnupg
  - lynx
  - ncdu
  - neovim
  - python
  - rsync
  - tree
  - wget
  - zsh
  - coreutils
  - btop
  - kitty
  - starship
  - lsd
  - yazi
  - fzf
  - ripgrep
  - yt-dlp
  - powershell
  - zip
  - pipx
