common_core_debian_packages:
  - apt-transport-https
  - aria2
  - build-essential
  - ca-certificates
  - curl
  - git
  - gnupg
  - lynx
  - mosh
  - ncdu
  - neovim
  - nfs-common
  - plocate
  - python3
  - python3-pip
  - python3-venv
  - rsync
  - software-properties-common
  - ssh
  - tree
  - wget
  - zsh
  - ddate
  - sysstat
  - iotop
  - iftop
  - unzip
  - fontconfig
  - fonts-hack
  - pipx
  - bat
  - fd-find
  - tmux
  - zoxide
